# Generated by Django 3.0.4 on 2020-04-06 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('canvan', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='columna',
            old_name='tabler',
            new_name='tablero',
        ),
    ]
