# Generated by Django 3.0.4 on 2020-04-06 13:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('canvan', '0002_auto_20200406_0148'),
    ]

    operations = [
        migrations.AddField(
            model_name='tablero',
            name='fecha_ultima_modificacion',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
