# Generated by Django 3.0.4 on 2020-03-23 18:36

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200323_0640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulo',
            name='contenido',
            field=tinymce.models.HTMLField(),
        ),
    ]
